package jsettlers.common.sound;

public enum ESoundType {
    LUMBERJACK,                 // 0
    BRICKLAYER,                 // 1
    DIGGER,                     // 2
    STONECUTTER,                // 3
    PLANT_TREE,                 // 4
    SAWMILLER,                  // 5
    SMITH_A,                    // 6
    SMITH_B,                    // 7
    FARMER_A,                   // 8
    FARMER_B,                   // 9
    UNKNOWN_10,                 // 10
    UNKNOWN_11,                 // 11
    FARMER_C,                   // 12
    FIRE,                       // 13
    DYING_PIG,                  // 14
    FISHERMAN_A,                // 15
    FISHERMAN_B,                // 16
    FISHERMAN_C,                // 17
    UNKNOWN_18,                 // 18
    UNKNOWN_19,                 // 19
    DOCKYARD,                   // 20
    HEALER,                     // 21
    UNKNOWN_22,                 // 22
    UNKNOWN_23,                 // 23
    GEOLOGIST,                  // 24
    BOWMAN,                     // 25
    UNKNOWN_26,                 // 26
    UNKNOWN_27,                 // 27
    UNKNOWN_28,                 // 28
    UNKNOWN_29,                 // 29
    SWORD_SOLDIER,              // 30
    SOLDIER_A,                  // 31
    SOLDIER_B,                  // 32
    BOWMAN_ALT,                 // 33
    PIKEMAN,                    // 34
    SOLDIER_KILLED,             // 35
    FALLING_TREE,               // 36
    MOLTEN_METAL_A,             // 37
    MOLTEN_METAL_B,             // 38
    PIGS,                       // 39
    DONKEY_A,                   // 40
    DONKEY_B,                   // 41
    WINDMILL,                   // 42
    DISTILLERY_A,               // 43
    DISTILLERY_B,               // 44
    CHARCOAL_BURNER,            // 45
    PLACE_BUILDING,             // 46
    UI_INCREASE,                // 47
    UI_DECREASE,                // 48
    UI_INCREASE_MAX,            // 49
    UI_DECREASE_MAX,            // 50
    BUILDING_DESTRUCTION,       // 51
    SET_DISTRIBUTION,           // 52
    UI_CLICK_A,                 // 53
    PAUSE_CONSTRUCTION,         // 54
    GUI_ACCEPT,                 // 55
    GUI_DENY,                   // 56
    MOVE_ACTION,                // 57
    NOTIFICATION_A,             // 58
    NOTIFICATION_B,             // 59
    UI_CLICK_B,                 // 60
    UI_CLICK_GENERAL,           // 61
    UI_CLICK_D,                 // 62
    UI_CLICK_E,                 // 63
    UI_CLICK_F,                 // 64
    UI_CLICK_G,                 // 65
    UI_CLICK_H,                 // 66
    DESERT,                     // 67
    SEA_A,                      // 68
    BIRD_A,                     // 69
    BIRD_B,                     // 70
    WATER_RIVER,                // 71
    MOOR,                       // 72
    WIND,                       // 73
    CRAZY_WIND,                 // 74
    THUNDER_A,                  // 75
    RAIN_A,                     // 76
    HEHEHE,                     // 77
    GIFTS,                      // 78
    COAST_WAVE,                 // 79
    BEING_ATTACKED,             // 80
    MILL_A,                     // 81
    MILL_B,                     // 82
    MILL_C,                     // 83
    CATAPULT,                   // 84
    ARROW_SHOT,                 // 85
    CANON_SHOT_A,               // 86
    CANON_SHOT_B,               // 87
    CANON_SHOT_C,               // 88
    CANON_SHOT_D,               // 89
    CANON_SHOT_E,               // 90
    FIRE_ALT,                   // 91
    SMALL_FIRE,                 // 92
    COLLAPSING_BUILDING,        // 93
    HEALING,                    // 94
    SET_WORKER_AREA,            // 95
    UNKNOWN_96,                 // 96
    UNKNOWN_97,                 // 97
    UNKNOWN_98,                 // 98
    UNKNOWN_99,                 // 99
    ATTACKED_A,                 // 100
    ATTACKED_B,                 // 101
    ATTACKED_C,                 // 102
    ATTACKED_D,                 // 103
    ATTACKED_E,                 // 104
    ATTACKED_F,                 // 105
    ATTACKED_G,                 // 106
    ATTACKED_H,                 // 107
    ATTACKED_I,                 // 108
    ATTACKED_J,                 // 109
    MISSING_TOOL,               // 110
    GONG_A,                     // 111
    GONG_B,                     // 112
    AMAZON_KILLED_A,            // 113
    UNKNOWN_114,                // 114
    UNKNOWN_115,                // 115
    REFUSED,                    // 116
    BEES                        // 117
}